<?php

function bt_get_section_anims() {
	
	$anims = array(
		'' => '',
		__( 'Move to left | from right', 'bt_plugin' ) => '1',
		__( 'Move to right | from left', 'bt_plugin' ) => '2',
		__( 'Move to top | from bottom', 'bt_plugin' ) => '3',
		__( 'Move to bottom | from top', 'bt_plugin' ) => '4',
		__( 'Fade | from right', 'bt_plugin' ) => '5',
		__( 'Fade | from left', 'bt_plugin' ) => '6',
		__( 'Fade | from bottom', 'bt_plugin' ) => '7',
		__( 'Fade | from top', 'bt_plugin' ) => '8',
		__( 'Fade left | Fade right', 'bt_plugin' ) => '9',
		__( 'Fade right | Fade left', 'bt_plugin' ) => '10',
		__( 'Fade top | Fade bottom', 'bt_plugin' ) => '11',
		__( 'Fade bottom | Fade top', 'bt_plugin' ) => '12',
		__( 'Different easing | from right', 'bt_plugin' ) => '13',
		__( 'Different easing | from left', 'bt_plugin' ) => '14',
		__( 'Different easing | from bottom', 'bt_plugin' ) => '15',
		__( 'Different easing | from top', 'bt_plugin' ) => '16',
		__( 'Scale down | from right', 'bt_plugin' ) => '17',
		__( 'Scale down | from left', 'bt_plugin' ) => '18',
		__( 'Scale down | from bottom', 'bt_plugin' ) => '19',
		__( 'Scale down | from top', 'bt_plugin' ) => '20',
		__( 'Scale down | scale down', 'bt_plugin' ) => '21',
		__( 'Scale up | scale up', 'bt_plugin' ) => '22',
		__( 'Move to left | scale up', 'bt_plugin' ) => '23',
		__( 'Move to right | scale up', 'bt_plugin' ) => '24',
		__( 'Move to top | scale up', 'bt_plugin' ) => '25',
		__( 'Move to bottom | scale up', 'bt_plugin' ) => '26',
		__( 'Scale down | scale up', 'bt_plugin' ) => '27',
		__( 'Glue left | from right', 'bt_plugin' ) => '28',
		__( 'Glue right | from left', 'bt_plugin' ) => '29',
		__( 'Glue bottom | from top', 'bt_plugin' ) => '30',
		__( 'Glue top | from bottom', 'bt_plugin' ) => '31',
		__( 'Flip right', 'bt_plugin' ) => '32',
		__( 'Flip left', 'bt_plugin' ) => '33',
		__( 'Flip top', 'bt_plugin' ) => '34',
		__( 'Flip bottom', 'bt_plugin' ) => '35',
		__( 'Push left | from right', 'bt_plugin' ) => '38',
		__( 'Push right | from left', 'bt_plugin' ) => '39',
		__( 'Push top | from bottom', 'bt_plugin' ) => '40',
		__( 'Push bottom | from top', 'bt_plugin' ) => '41',
		__( 'Push left | pull right', 'bt_plugin' ) => '42',
		__( 'Push right | pull left', 'bt_plugin' ) => '43',
		__( 'Push top | pull bottom', 'bt_plugin' ) => '44',
		__( 'Push bottom | pull top', 'bt_plugin' ) => '45',
		__( 'Fold left | from right', 'bt_plugin' ) => '46',
		__( 'Fold right | from left', 'bt_plugin' ) => '47',
		__( 'Fold top | from bottom', 'bt_plugin' ) => '48',
		__( 'Fold bottom | from top', 'bt_plugin' ) => '49',
		__( 'Move to right | unfold left', 'bt_plugin' ) => '50',
		__( 'Move to left | unfold right', 'bt_plugin' ) => '51',
		__( 'Move to bottom | unfold top', 'bt_plugin' ) => '52',
		__( 'Move to top | unfold bottom', 'bt_plugin' ) => '53',
		__( 'Room to left', 'bt_plugin' ) => '54',
		__( 'Room to right', 'bt_plugin' ) => '55',
		__( 'Room to top', 'bt_plugin' ) => '56',
		__( 'Room to bottom', 'bt_plugin' ) => '57',
		__( 'Cube to left', 'bt_plugin' ) => '58',
		__( 'Cube to right', 'bt_plugin' ) => '59',
		__( 'Cube to top', 'bt_plugin' ) => '60',
		__( 'Cube to bottom', 'bt_plugin' ) => '61',
		__( 'Carousel to left', 'bt_plugin' ) => '62',
		__( 'Carousel to right', 'bt_plugin' ) => '63',
		__( 'Carousel to top', 'bt_plugin' ) => '64',
		__( 'Carousel to bottom', 'bt_plugin' ) => '65',
		__( 'Sides', 'bt_plugin' ) => '66',
		__( 'Slide', 'bt_plugin' ) => '67'
	);

	return $anims;

}